# Prometheus Values
prometheus_image: "registry.access.redhat.com/openshift3/prometheus"
prometheus_version: "v3.11"
prometheus_port: 9090
prometheus_proxy_port: 4180

# Grafana values
grafana_image: "registry.access.redhat.com/openshift3/grafana"
grafana_version: "v3.11"
grafana_port: 3000
grafana_proxy_port: 4181
grafana_log_level: debug
grafana_admin_username: admin

# Api server values
api_server_image: "docker.io/aerogear/aerogear-app-metrics"
api_server_version: "0.0.12"
api_server_port: 3000

# Postgres values
postgres_image: "registry.access.redhat.com/rhscl/postgresql-96-rhel7"
postgres_version: "1"
postgres_port: 5432
postgres_user: "{{ POSTGRES_USER | default('user', true) }}"
postgres_password: "{{ POSTGRES_PASSWORD | default(lookup('password', '/tmp/pass chars=ascii_letters,digits'), true) }}"
postgres_database: "aerogear_mobile_metrics"

# OAuth Proxy values
proxy_image: "registry.access.redhat.com/openshift3/oauth-proxy"
proxy_version: "v3.11"

# Keycloak values
keycloak_dashboard_configmap_name: keycloak-dashboard.json