prometheus_image: "docker.io/prom/prometheus"
prometheus_version: "v2.0.0"
prometheus_port: 9090
prometheus_configmap_name: "prometheus-configmap"
prometheus_configmap_volume_name: "prometheus-configmap-volume"
prometheus_secret_name: "prometheus"
prometheus_proxy_port: 4180
# Grafana values
grafana_image: "docker.io/grafana/grafana"
# TODO: Change to 4.7.0 when a tag is available
grafana_version: "master"
grafana_port: 3000
grafana_ini_configmap_name: "grafana-ini-configmap"
grafana_ini_configmap_volume_name: "grafana-ini-configmap-volume"
grafana_datasources_configmap_name: "grafana-datasources-configmap"
grafana_datasources_configmap_volume_name: "grafana-datasources-configmap-volume"
grafana_dashboards_configmap_name: "grafana-dashboards-configmap"
grafana_dashboards_configmap_volume_name: "grafana-dashboards-configmap-volume"
grafana_proxy_port: 4181
# OAuth Proxy values
proxy_serviceaccount_name: "oauth-proxy"
proxy_image: "docker.io/openshift/oauth-proxy"
proxy_version: "v1.1.0"